import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "CafeX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className="bg-[#e2ead8] dark:bg-gray-800">
      <div className="container">{children}</div>
      </body>
    </html>
  );
}
