import type { Metadata } from "next";
import "./globals.css";
import SessionContextGlobal from "./context/SessionContext";

export const metadata: Metadata = {
  title: "CafeX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es">
      <body className="bg-[#edf5e3] dark:bg-gray-800">
      <SessionContextGlobal>
          <div className="container">
            {children}
          </div>
        </SessionContextGlobal>
      </body>
    </html>
  );
}
